from snakemake.utils import validate

configfile : "config/workflowsettings.yaml"
validate(config,"schemas/config.schema.yaml")

include: "rules/create_cases.smk"
include: "rules/prep.smk"

rule all:
    input : *get_casefiles(), *get_polymesh(), *get_setsdir()
