rule blade_loading:
#    input:
#        "input/helloworld.txt"
#    output:
#        "output/heythere.txt"
    script:
        "python helloworld.py"

rule operating_point:
#    input:
#        "input/helloworld.txt"
#    output:
#        "output/heythere.txt"
    shell:
        "python helloworld.py"

rule operating_point:
#    input:
#        "input/helloworld.txt"
#    output:
#        "output/heythere.txt"
    shell:
        "python helloworld.py"

