#todo make part of validation
basedir = workflow.current_basedir

rule profile_from_pointcloud:
    input :
        "00_resources/{profile_name}.txt"
    output:
        "01_profile/{profile_name}_sortedPoints.txt",
        "01_profile/{profile_name}_psPoly.vtk",
        "01_profile/{profile_name}_ssPoly.vtk",
        "01_profile/{profile_name}_midsPoly.vtk",
        "01_profile/{profile_name}_geometry_paras.yml",
        "01_profile/{profile_name}_profile.pdf"

    params:
        algorithm=config["blade"]["algorithm"],
        pointcloud = config["blade"]["ptcloud_profile"],
        unit = config["blade"]["ptcloud_profile_unit"],
        alpha = config["blade"]["alpha"]

    run:
#        from ntrfc.preprocessing.geometry_creation.profile_pointcloud import generate_profile_pointcloud_geometry
        print(wildcards.profile_name)
#        generate_profile_pointcloud_geometry(basedir,**params)
