blade:
    algorithm: "from_pointcloud"
    ptcloud_profile: "00_Ressources/profile_pointcloud.txt"   #Name of the pointcloud-file
    ptcloud_profile_unit: "mm"                                  #m vs mm

geometry:
    pitch                           : 0.0765                                #Pitch [m]
    alpha                           : 0.01                                  #Geometric parameter used for hull-calculations
    midline_tolerance               : 5                                     #Tolerance coefficient for midline-generation
    x_inlet                         : -0.13                                 #Shift Inlet along x [m]
    x_outlet                        : 0.26                                  #Shift Outlet along x [m]
    shift_domain                    : 0.015                                 #Shift Domain to have probes inside domain [m]
