rule from_pointcloud:
#    input:
#        "input/helloworld.txt"
#    output:
#        "output/heythere.txt"
    script:
        "python helloworld.py"

rule from_naca_generator:
#    input:
#        "input/helloworld.txt"
#    output:
#        "output/heythere.txt"
    shell:
        "python helloworld.py"

rule create_parsec_generator:
#    input:
#        "input/helloworld.txt"
#    output:
#        "output/heythere.txt"
    shell:
        "python helloworld.py"
