from snakemake.utils import validate
from snakemake.utils import Paramspace
import pandas as pd

import os

#todo move this snakepipe to according dir in sourcecode

configfile : "casesettings.yaml"
validate(config,"config.schema.yaml")
basedir = workflow.current_basedir

# declare a dataframe to be a paramspace
PARAMS=pd.read_csv("caseparams.tsv", sep="\t")
validate(PARAMS, "case.schema.yaml")
paramspace = Paramspace(PARAMS)
#paramspace.param_sep="-"
#paramspace.pattern="{}~{}~{}"


def get_template_path():
    import ntrfc
    templatepath = os.path.join(os.path.dirname(ntrfc.__file__),"database","case_templates")
    return templatepath

def create_filelist_from_template(template):
    """
    :param template: path
    :return: list of files
    """
    from ntrfc.utils.dictionaries.dict_utils import nested_dict_pairs_iterator
    from case_creation import  get_directory_structure
    templatepath = os.path.join(get_template_path(),template)
    assert os.path.isdir(os.path.join(templatepath))
    files = list(nested_dict_pairs_iterator(get_directory_structure(templatepath)))
    fpaths = [os.path.join(*i[:-1]) for i in files]
    return fpaths


TEMPLATE = config["case_params"]["case_type"]
TEMPLATE_PATH = os.path.join(get_template_path(),TEMPLATE)
DATASETS = create_filelist_from_template(TEMPLATE)

rule all:
    input:
        # Aggregate over entire parameter space (or a subset thereof if needed)
        # of course, something like this can happen anywhere in the workflow (not
        # only at the end).
        *[f"{instance_pattern}/{file}" for instance_pattern in paramspace.instance_patterns for file in DATASETS]

rule create_case:
    input:
        [f"{templatepath}/{file}" for templatepath in [get_template_path()] for file in DATASETS ]
    output:
        # format a wildcard pattern like "alpha~{alpha}/beta~{beta}/gamma~{gamma}"
        # into a file path, with alpha, beta, gamma being the columns of the data frame
        *[f"{paramspace.wildcard_pattern}/{file}" for file in DATASETS]
    params:
        case_type = config["case_params"]["case_type"],
        # automatically translate the wildcard values into an instance of the param space
        # in the form of a dict (here: {"alpha": ..., "beta": ..., "gamma": ...})
        simulation=paramspace.instance
    run:
        from case_creation import create_case
        create_case(input, output,params["case_type"],params["simulation"])
