$schema: http://json-schema.org/draft-04/schema#
properties:
  geometry:
    properties:
      alpha:
        properties:
          default:
            type: string
          value:
            type: number
        required:
        - default
        - value
        type: object
      unit:
        properties:
          default:
            type: string
          m:
            type: string
          mm:
            type: string
        required:
        - default
        - mm
        - m
        type: object
    required:
    - unit
    - alpha
    type: object
  meshing:
    properties:
      param1:
        properties:
          default:
            type: string
          value1:
            type: string
          value2:
            type: string
        required:
        - default
        - value1
        - value2
        type: object
      param2:
        properties:
          default:
            type: string
          value1:
            type: string
          value2:
            type: string
        required:
        - default
        - value1
        - value2
        type: object
    required:
    - param1
    - param2
    type: object
  create_case:
    properties:
      command:
        type: string
      default:
        type: string
    required:
    - default
    - command
    type: object
  run_simulation:
    properties:
      default:
        type: string
      fall1:
        type: string
      fall2:
        type: string
    required:
    - default
    - fall1
    - fall2
    type: object
  post_processing:
    properties:
      param1:
        properties:
          default:
            type: string
          value1:
            type: string
          value2:
            type: string
        required:
        - default
        - value1
        - value2
        type: object
    required:
    - param1
    type: object
required:
- geometry
- meshing
- create_case
- run_simulation
- post_processing
type: object
