# The config file that determine the used parameter in each step of simulation.

mesh:
    param1: ["mesh1", "mesh2"]         # type of meshing
    param2: ["value1", "value2"]       # quality of meshing

case:
    my_case: "infos.txt"               # all infos about this case as txt file

run:
    param: "execute"                   # parameters that used to execute the simulation

post_processing:
    param: "result"                    # analyse the results after simulation
