WorkflowSteps:
  Creat_Geometry:
    alpha: 0.05
    unit:
    - mm
    - m
  Choose_the_Case:
      Case_Number:
          cae1: templets1
          case2: templets2
  Mesh_generation:
    quality:
    - Good
    - Perfect
    type:
    - mesh1
    - mesh2
  Running_the_Simulation:
    Falls:
      fall1: simulation1
      fall2: simlation2
  Post_Processing:
      results:
          analyse: analyse
          rating: rate
