from snakemake.utils import validate


configfile: "config.yaml"
validate(config, "config.schema.yaml")


rule mesh:
    output:
        r"meshing/mesh1.txt", r"meshing/mesh2.txt"
    shell:
        "touch {output}"

